name: pangeo
channels:
 - conda-forge
 - nodefaults
dependencies:
 - python=3.*
 # - pangeo-notebook>=2023.03.15
 - pangeo-dask =2024.03.18
 - dask-labextension =7.0.0
 - ipywidgets =8.1.2
 - jupyter-server-proxy =4.1.2
 - jupyterhub-singleuser =3.0.0
 - jupyterlab =4.1.5
 - nbgitpuller =1.2.0

 - adlfs
 - argopy
 - awscli
 - black
 - boto3
 - bottleneck
 - cartopy
 - cdsapi
 - cfgrib
 - cf_xarray
 - ciso
 - cmocean
 - dask-ml
 - dask-cloudprovider
 - datashader
 - descartes
 - earthaccess
 - eofs
 - erddapy
 - esmpy
 - fastjmd95
 - flox
 - fsspec
 - gcm_filters
 - gcsfs
 - gh
 - gh-scoped-creds
 - geocube
 - geopandas
 - geopy
 - geoviews-core
 - git-lfs
 - gsw
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipdb
 - ipykernel
 - ipyleaflet
 - ipytree
 - ipywidgets
 - jupyterlab_code_formatter
 - jupyterlab-git
 - jupyterlab-myst
 - jupyter-panel-proxy
 - jupyter-resource-usage
 - kerchunk
 - line_profiler
 - lxml
 - lz4
 - matplotlib-base
 - memory_profiler
 - metpy
 - nb_conda_kernels
 - nbstripout
 - nc-time-axis
 - netcdf4
 - numbagg
 - numcodecs
 - numpy
 - numpy_groupies
 - odc-stac
 - pandas
 - panel
 - parcels
 - param
 - pop-tools
 - pyarrow
 - pycamhd
 - pydap
 - pystac
 - pystac-client
 - python-blosc
 - python-gist
 - python-graphviz
 - python-xxhash
 - rasterio
 - rechunker
 - rio-cogeo
 - rioxarray
 - s3fs
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - seaborn
 - sparse
 - snakeviz
 - stackstac
 - tiledb-py
 - timezonefinder
 - watermark
 - xarray
 - xarrayutils
 - xarray-datatree
 - xarray_leaflet
 - xarray-spatial
 - xbatcher
 - xcape
 - xclim
 - xesmf
 - xgboost
 - xgcm
 - xhistogram
 - xmip
 - xmitgcm
 - xpublish
 - xrft
 - xskillscore
 - xxhash
 - zarr
 # tensorflow
 - flax
 - jax
 - jupyterlab-nvdashboard
 - keras-cv
 - tensorflow>=2.14.0=*cuda118*
