name: PR Build
on:
  pull_request:
    branches:
      - main

jobs:
  matrix-build:
    strategy:
      fail-fast: false
      matrix:
        IMAGE: [python, r, gpu-pytorch, gpu-tensorflow, qgis]

    name: ${{ matrix.IMAGE }}
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to ghcr.io registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      uses: docker/build-push-action@v3
      with:
        push: false
        context: ${{ matrix.IMAGE }}
        builder: ${{ steps.buildx.outputs.name }}
        outputs: type=docker,dest=image.tar

    - name: Test image
      id: test
      run: |
        docker load --input image.tar
        docker ps
        docker images
        docker images -q
        export IMG=$(docker images -q | head -n1)
        docker run --rm -v ${PWD}/.github/workflows/scripts:/scripts $IMG /scripts/${{ matrix.IMAGE }}
